import { campaignWords } from './chapters.js';
export const words = {
  ...campaignWords,
  title: ['静默子午线', 'Silent Meridian'],
  subtitle: ['一座观测站。一个没有结束的夜晚。', 'One observatory. One night that never ended.'],
  tagline: ['世界停在 00:17。\n只有你的影子，还在往前走。', 'The world stopped at 00:17.\nYour shadow kept moving.'],
  enter: ['进入观测站', 'Enter the observatory'],
  resume: ['继续调查', 'Continue investigation'],
  newGame: ['重新开始', 'Begin again'],
  prologue: ['海岸观测计划 / 第 09 号站', 'COASTAL OBSERVATION / STATION 09'],
  original: ['原创交互解谜', 'AN ORIGINAL PUZZLE EXPERIENCE'],
  credit: ['静默子午线 · 第一章：未竟之夜', 'SILENT MERIDIAN · CHAPTER I: THE UNFINISHED NIGHT'],
  soundOn: ['关闭声音', 'Mute sound'], soundOff: ['开启声音', 'Enable sound'],
  depthEnable: ['开启 3D 视效', 'Enable 3D effects'],
  depthDisable: ['关闭 3D 视效', 'Disable 3D effects'],
  depthDescription: ['移动鼠标感受景深；触屏下镜头轻缓漂移。调查机关时画面会停稳。', 'Move the pointer to explore the depth; touch screens use a gentle camera drift. The view settles while inspecting an instrument.'],
  depthStill: ['已跟随系统的“减少动态效果”设置：保留立体光影，关闭镜头移动与动画。', 'Following your reduced-motion preference: dimensional lighting remains, with no camera movement or animation.'],
  depthUnavailable: ['此设备使用基础画面，所有谜题仍可正常游玩。', 'This device uses the basic view. Every puzzle remains playable.'],
  journal: ['调查手记', 'Field journal'], map: ['观测站平面图', 'Station map'],
  present: ['现在', 'Present'], echo: ['回声', 'Echo'],
  shift: ['切换时间 · 空格', 'Shift time · Space'],
  presentTime: ['时间静止', 'TIME SUSPENDED'], echoTime: ['前一分钟的残影', 'THE MINUTE BEFORE'],
  back: ['返回场景', 'Back to the room'], close: ['关闭', 'Close'],
  inspect: ['调查', 'Inspect'], mechanisms: ['已校准', 'CALIBRATED'],
  saved: ['进度已保存', 'Progress saved'], noSave: ['本次浏览器无法保存进度，请保持页面打开。', 'Saving is unavailable in this browser. Keep this page open.'],
  noNotes: ['尚未收集到线索。试着检查房间里发光的物件。', 'No evidence yet. Inspect the glowing objects in each room.'],
  recorded: ['线索已收入手记', 'Evidence added to your journal'],
  fieldNotes: ['我的推理', 'My deductions'], notesPlaceholder: ['记下符号、数字或你的猜想……', 'Record symbols, numbers, or a theory…'],
  personalSaved: ['文字随进度自动保存在此浏览器', 'Your writing saves with your progress in this browser'],
  evidence: ['线索档案', 'Evidence archive'], allEvidence: ['全部线索', 'All evidence'],
  collected: ['已收集', 'COLLECTED'], optional: ['可选', 'OPTIONAL'],
  help: ['操作说明', 'How to play'], settings: ['暂停与设置', 'Pause & settings'],
  controls: ['点击场景物件调查；下方切换房间。空格切换时间，J 打开手记，Esc 返回。', 'Inspect objects in the scene. Travel using the rooms below. Space shifts time, J opens the journal, and Esc goes back.'],
  touchControls: ['点击发光物件调查，切换房间寻找线索。同一个地方，在“现在”和“回声”里会留下不同的记录。', 'Tap glowing objects and explore every room. The same place holds different records in the Present and in the Echo.'],
  briefingTitle: ['你来过这里。只是不记得了。', 'You have been here. You just do not remember.'],
  briefingBody: ['海水悬在半空，穹顶上的钟停在 00:17。口袋里的相位仪却仍在工作——它能让你看见前一分钟留下的回声。\n\n找到三处失准的装置，再回到主星盘。这里的每一道锁，都有留下的答案。', 'The sea hangs motionless. The clock above the dome reads 00:17. Only the phase instrument in your pocket still works: it reveals an echo of the preceding minute.\n\nRestore three instruments, then return to the meridian. Every lock here has left its answer somewhere.'],
  beginInvestigation: ['开始调查', 'Begin investigation'],
  noTimer: ['自由探索 · 无倒计时 · 自动存档', 'EXPLORE FREELY · NO TIMER · AUTOSAVE'],
  resetTitle: ['重新开始这一个夜晚？', 'Begin this night again?'],
  resetBody: ['这会清除本游戏在此浏览器中的谜题进度、手记与结局。', 'This clears this game’s puzzle progress, journal, and ending in this browser.'],
  cancel: ['保留进度', 'Keep progress'], confirmReset: ['清除并重新开始', 'Clear and restart'],
  showMarkers: ['显示调查点', 'Show investigation points'],
  hideMarkers: ['隐藏调查点', 'Hide investigation points'],
  titleScreen: ['返回标题画面', 'Return to title'],
  hint: ['需要一点提示', 'A little help'], nextHint: ['再多一点提示', 'Reveal another hint'],
  hintLevel: ['提示层级', 'HINT LEVEL'], lastHint: ['全部提示已展开', 'All hints revealed'],
  resetPuzzle: ['复位机关', 'Reset instrument'], check: ['验证排列', 'Check sequence'],
  tune: ['锁定频段', 'Lock frequencies'], calibrate: ['校准潮汐', 'Calibrate tide'], align: ['锚定主镜', 'Anchor the meridian'],
  wrong: ['机关没有响应。还有线索没有吻合。', 'The instrument remains silent. A clue still does not fit.'],
  solved: ['校准完成', 'CALIBRATION COMPLETE'], returnExplore: ['继续探索', 'Continue exploring'],
  alreadySolved: ['这台装置已经校准。结果已记录在手记中。', 'This instrument is calibrated. Its result is in your journal.'],
  relatedNotes: ['随手查阅线索', 'Evidence at hand'],
  missingNote: ['尚未找到：', 'Not yet found: '],
  archiveTitle: ['到站者档案', 'The arrivals archive'],
  archiveIntro: ['五位观测员，五枚标记。把他们按抵达先后，从左至右排列。', 'Five observers, five emblems. Arrange them from first arrival to last, left to right.'],
  archiveInstruction: ['先选槽位，再选符号。已放入的符号会与当前槽位交换。', 'Select a slot, then an emblem. Placed emblems swap with the selected slot.'],
  slot: ['槽位', 'Slot'], selected: ['已选', 'Selected'], empty: ['空槽', 'Empty'],
  radioTitle: ['回声接收器', 'The echo receiver'],
  radioIntro: ['这段信号不是从远方传来。三个频段，指向同一个时间。', 'The signal is not coming from somewhere far away. Three frequencies point to a single moment.'],
  radioInstruction: ['调整三个频段的数值。磁带上的线索与到站档案有关。', 'Tune all three bands. The tape refers to the order in the arrivals archive.'],
  band: ['频段', 'BAND'], playSignal: ['监听信号', 'Listen to signal'],
  signalVisual: ['波形与数值均为可视线索，无需依赖声音。', 'All information is visible in the values and waveform; audio is optional.'],
  tideTitle: ['停潮机', 'The stillwater engine'],
  tideIntro: ['四根指针互相牵动。你转动的，从来不只有一枚齿轮。', 'Four hands pull against each other. No wheel ever turns alone.'],
  tideInstruction: ['每圈八格，顺时针递增。＋顺转一格，−逆转一格；四针归零才会停潮。', 'Eight marks per circle, increasing clockwise. + advances and − reverses. Bring all four hands to zero.'],
  coupling: ['传动关系', 'COUPLING SCHEMATIC'],
  tideReset: ['复位后恢复初始刻度，不影响其他装置。', 'Reset restores the original positions without affecting other instruments.'],
  tidePlan: ['从当前刻度出发：', 'From the current positions: '],
  tideHintReady: ['四针已归零，现在可以校准。', 'All hands are at zero. Calibrate now.'],
  turnPlus: ['顺转', 'Forward'], turnMinus: ['逆转', 'Backward'],
  meridianTitle: ['静默子午线', 'The silent meridian'],
  meridianIntro: ['潮汐、到站者、无线电。三条看似无关的记录，在这里汇合。', 'The tide, the arrivals, the radio. Three unrelated records meet here.'],
  inner: ['内轨', 'INNER'], middle: ['中轨', 'MIDDLE'], outer: ['外轨', 'OUTER'],
  meridianInstruction: ['三条轨道均有八格，从 0 开始。按镜架铭文，由内向外设定刻度。', 'Each orbit has eight marks, starting at 0. Read the lens inscription from the inner orbit outward.'],
  stillLocked: ['三处装置尚未全部校准。主镜缺少稳定的参照。', 'The three instruments are not yet calibrated. The meridian has no stable reference.'],
  requireEcho: ['主镜只接受回声中的锚定。切换至“回声”，再对齐轨道。', 'The meridian can only be anchored in the Echo. Shift there to align its orbits.'],
  toEcho: ['切换至回声', 'Shift to the Echo'], toPresent: ['带着锚点回到现在', 'Carry the anchor to the Present'],
  anchored: ['锚点已经留在前一分钟。现在，回去让时钟继续。', 'Your anchor is in the preceding minute. Return to the Present and let the clock move.'],
  releaseTime: ['让时间继续', 'Let time move'],
  finishTitle: ['无线电里，是你自己的声音。', 'The voice on the radio is yours.'],
  finishBody: ['这座站并没有困住你。它在替海岸上的人们留住最后一分钟。\n\n现在，信号已经送达，海堤的灯也已经亮起。你可以松开这根指针了。\n\n那段引导你走到这里的回声，要留下吗？', 'The station was not keeping you prisoner. It was holding the coast’s last minute open.\n\nNow the signal has arrived. The seawall lights are on. You can let go of the clock’s hand.\n\nWill you leave the echo that guided you here?'],
  keepEcho: ['留下回声', 'Leave the echo'], releaseEcho: ['让回声消散', 'Let it fade'],
  endKeepTitle: ['致下一位守夜人', 'For the next keeper'],
  endReleaseTitle: ['终于，明天', 'Tomorrow, at last'],
  endKeep: ['你把那句话录进磁带。\n“如果你听到了，不要害怕。”\n\n时钟走到了 00:18。海风第一次穿过穹顶。\n很久以后，也许会有另一个人，听见你的声音。', 'You press record.\n“If you can hear this, do not be afraid.”\n\nThe clock turns to 00:18. Sea air passes through the dome for the first time.\nSomeday, someone else may hear your voice.'],
  endRelease: ['你按下抹除键，沙沙声渐渐退去。\n这一次，不再有人重复昨天。\n\n时钟走到了 00:18。海面升起第一道真正的浪。\n在这座站之外，还有一个明天。', 'You erase the tape. The static slowly disappears.\nThis time, no one has to repeat yesterday.\n\nThe clock turns to 00:18. The first real wave rises on the sea.\nOutside the station, there is a tomorrow.'],
  finished: ['调查完成', 'INVESTIGATION COMPLETE'],
  endingLabel: ['结局', 'ENDING'], reviewJournal: ['重读手记', 'Read the journal'],
  exploreAfter: ['回到观测站', 'Revisit the observatory'],
  objectiveStart: ['调查三个房间，让装置重新归位。', 'Explore the three rooms. Restore their instruments.'],
  objectiveFinal: ['三处装置已经校准。回到穹顶，解开主星盘。', 'Three instruments restored. Return to the dome and align the meridian.'],
  objectiveAnchor: ['锚点已留在回声中。回到现在，启动主镜。', 'The Echo holds your anchor. Return to the Present and release the meridian.'],
  objectiveDone: ['00:18。海水终于开始流动。', '00:18. The sea moves again.'],
  phaseHint: ['同一间房间，在另一段时间里藏着不同的线索。', 'The same room holds different evidence in the other moment.'],
  settingsBody: ['游戏随每次操作自动保存。声音只用于营造氛围；所有谜题都能依靠视觉线索完成。', 'Progress saves after every action. Sound is atmospheric; every puzzle can be solved using visual evidence.'],
  progress: ['调查进度', 'Investigation progress'],
};

export const symbols = {
  diamond: { glyph: '◇', name: ['棱', 'Diamond'] },
  wave: { glyph: '≋', name: ['潮', 'Tide'] },
  peak: { glyph: '△', name: ['峰', 'Peak'] },
  sun: { glyph: '⊙', name: ['日', 'Sun'] },
  star: { glyph: '✶', name: ['星', 'Star'] },
};

export const rooms = {
  observatory: { number: '01', name: ['观测穹顶', 'The dome'], sub: ['子午线观测室', 'MERIDIAN OBSERVATORY'], description: ['一整片夜空，被悬在一根不动的指针上。', 'An entire night balances on a motionless hand.'], puzzle: 'meridian', point: [64, 44], notePoint: [17, 84], echoPoint: [91, 65], note: ['welcome', 'last-letter'] },
  archive: { number: '02', name: ['档案室', 'The archive'], sub: ['到站者记录库', 'ARRIVALS & RECORDS'], description: ['五个人来过这里。有人擦掉了他们的名字。', 'Five people arrived. Someone erased their names.'], puzzle: 'archive', point: [55, 60], notePoint: [19, 75], echoPoint: [87, 45], note: ['arrival-a', 'arrival-b'] },
  radio: { number: '03', name: ['信号室', 'The signal room'], sub: ['远岸信号中继', 'COASTAL SIGNAL RELAY'], description: ['没有人说话，无线电却从未停止呼吸。', 'No one speaks. The radio has never stopped breathing.'], puzzle: 'radio', point: [57, 58], notePoint: [22, 56], echoPoint: [84, 65], note: ['radio-a', 'radio-b'] },
  cistern: { number: '04', name: ['潮汐井', 'The tidal well'], sub: ['水位与时间调节', 'TIDAL REGULATION'], description: ['这一滴水，已经下落了很多年。', 'This drop has been falling for years.'], puzzle: 'tide', point: [58, 46], notePoint: [17, 75], echoPoint: [86, 68], note: ['tide-a', 'tide-b'] },
};

export const notes = {
  welcome: { room: 'observatory', phase: 'present', title: ['没有署名的日志', 'The unsigned log'], body: ['00:17。\n\n如果你正在读这段话，说明观测站仍在等待。档案室记录“谁”，信号室记录“何时”，潮汐井负责让一切停下来。三处归位，主镜才会重新响应。\n\n相位仪能让你触碰前一分钟留下的回声。同一个房间，请看两遍。\n\n不要害怕那道声音。', '00:17.\n\nIf you are reading this, the observatory is still waiting. The archive remembers who. The radio remembers when. The tidal well keeps everything still. Restore all three and the meridian will respond.\n\nYour phase instrument reveals the preceding minute. Look at every room twice.\n\nDo not be afraid of the voice.'] },
  'meridian-rule': { room: 'observatory', phase: 'present', title: ['镜架铭文', 'The lens inscription'], body: ['由内向外，三个轨道依次记住：\n\nⅠ · 水面休止时，潮汐指针的刻度。\nⅡ · 日标观测员的到站位次。\nⅢ · 第三频段的读数。\n\n主镜属于前一分钟。必须在回声中锚定，再回到现在释放。', 'From the inner orbit outward, remember:\n\nI · The tide’s resting dial mark.\nII · The Sun observer’s place in the arrivals.\nIII · The reading of the third radio band.\n\nThe meridian belongs to the preceding minute. Anchor it in the Echo, then release it in the Present.'] },
  'last-letter': { room: 'observatory', phase: 'echo', title: ['还没有写完的信', 'The unfinished letter'], body: ['他们说海堤只差一分钟就能关闭。\n\n所以我把这一分钟折起来，放进观测站。潮汐、记忆、声音——三个参照足以让它不再流逝。\n\n如果我忘记了回去的路，就让这封信、这段声音，再带我走一次。\n\n字迹与你手记上的，一模一样。', 'They said the seawall needed one more minute to close.\n\nSo I folded that minute into the observatory. Tide, memory, sound: three references to keep it from passing.\n\nIf I forget the way back, let this letter and this voice guide me through it again.\n\nThe handwriting is exactly the same as yours.'] },
  'arrival-a': { room: 'archive', phase: 'present', title: ['被水浸过的到站簿', 'The waterlogged register'], body: ['名字已经无法辨认，标记却仍清晰：\n◇ 棱　≋ 潮　△ 峰　⊙ 日　✶ 星\n\n“日标观测员恰好是第三位。”\n“棱标观测员最后到站。”\n\n页边注：从最早到最晚，每人占据一个位置，标记不可重复。', 'The names have washed away. The emblems remain:\n◇ Diamond  ≋ Tide  △ Peak  ⊙ Sun  ✶ Star\n\n“The Sun observer arrived exactly third.”\n“The Diamond observer arrived last.”\n\nMargin note: earliest to latest; one person in each place, no repeated emblems.'] },
  'arrival-b': { room: 'archive', phase: 'echo', title: ['墙上的未干笔迹', 'Writing still wet on the wall'], body: ['回声里，空白的墙面浮出两句话：\n\n“星标紧挨在日标之前。”\n“潮标比峰标更早到站。”\n\n墙脚还留着一枚新鲜的脚印。它与你的鞋底吻合。', 'Two sentences emerge on the wall in the Echo:\n\n“The Star observer arrived immediately before the Sun.”\n“The Tide observer arrived before the Peak.”\n\nA fresh footprint remains beneath the writing. It matches your shoe.'] },
  'archive-result': { room: 'archive', phase: 'present', title: ['恢复的到站顺序', 'The restored arrivals'], body: ['Ⅰ ≋ 潮　→　Ⅱ ✶ 星　→　Ⅲ ⊙ 日　→　Ⅳ △ 峰　→　Ⅴ ◇ 棱\n\n抽屉缓缓打开。里面没有五份档案，只有同一位观测员的五张照片。不同的年份，同一张脸。\n\n记忆参照已经恢复。', 'I ≋ Tide → II ✶ Star → III ⊙ Sun → IV △ Peak → V ◇ Diamond\n\nThe drawers open. There are no five separate files, only five photographs of the same observer. Different years. The same face.\n\nThe memory reference is restored.'] },
  'radio-a': { room: 'radio', phase: 'present', title: ['接收器接线纸', 'The receiver wiring slip'], body: ['三个频段的取值范围为 0—9。\n\n“第一频段，以星标观测员的到站位次为准。”\n\n没有姓名，只有一枚六角星。答案也许留在档案室。', 'Each radio band reads from 0 to 9.\n\n“Band one takes the Star observer’s place in the arrivals.”\n\nNo name, only a six-pointed star. The answer may be in the archive.'] },
  'radio-b': { room: 'radio', phase: 'echo', title: ['倒转的磁带', 'The reversed tape'], body: ['一段声音穿过前一分钟：\n\n“第二频段，是第一频段的两倍。”\n“第三频段，比第二频段多二。”\n\n磁带停下之前，那个人说：\n“如果你听到了，不要害怕。”', 'A voice passes through the preceding minute:\n\n“Band two is twice band one.”\n“Band three is two more than band two.”\n\nBefore the tape stops, the person says:\n“If you can hear this, do not be afraid.”'] },
  'radio-result': { room: 'radio', phase: 'present', title: ['已锁定的信号', 'The locked signal'], body: ['三个频段：2 / 4 / 6。\n\n噪声消退，远处有人回答：“海堤关闭。我们都安全了。可以让时钟继续了。”\n\n然后，你听见自己的呼吸，从磁带的另一端传来。\n\n声音参照已经恢复。', 'The three bands: 2 / 4 / 6.\n\nThe static clears. A distant voice replies: “The seawall is closed. Everyone is safe. You can let the clock move.”\n\nThen you hear your own breathing from the other side of the tape.\n\nThe sound reference is restored.'] },
  'tide-a': { room: 'cistern', phase: 'present', title: ['停潮机维修铭牌', 'The engine service plate'], body: ['四针各有八个刻度，从北面的 0 开始顺时针递增，7 之后回到 0。\n\nA：Ⅰ、Ⅱ 各进一格。\nB：Ⅱ、Ⅲ 各进一格。\nC：Ⅲ、Ⅳ 各进一格。\nD：Ⅰ 进一格，Ⅳ 进两格。\n\n反转时，牵动的指针一同后退。', 'Each hand has eight marks, increasing clockwise from 0 at the top. After 7, it returns to 0.\n\nA: I and II each advance one mark.\nB: II and III each advance one mark.\nC: III and IV each advance one mark.\nD: I advances one; IV advances two.\n\nReversing moves the coupled hands backward.'] },
  'tide-b': { room: 'cistern', phase: 'echo', title: ['水面下的刻字', 'An inscription beneath the water'], body: ['回声里的水位比现在更低。台座上露出一句话：\n\n“四针同时指北，水面便忘记流动。”\n\n四个 0，不多一格，也不少一格。\n\n这曾经是一台让海水停下来的机器。现在，它将成为让时间继续的参照。', 'The water is lower in the Echo. An inscription appears on the pedestal:\n\n“When all four hands point north, the water forgets to move.”\n\nFour zeroes. Not a mark more, not a mark less.\n\nThis machine once stopped the sea. Now it will become the reference that lets time move.'] },
  'tide-result': { room: 'cistern', phase: 'present', title: ['归零的潮汐指针', 'The resting tide'], body: ['Ⅰ 0　Ⅱ 0　Ⅲ 0　Ⅳ 0\n\n四根指针归位，水面平整得像一面镜子。它映出穹顶，而穹顶明明在头顶数十米之外。\n\n潮汐参照已经恢复。休止刻度：0。', 'I 0   II 0   III 0   IV 0\n\nThe four hands settle. The water becomes a perfect mirror. It reflects the dome, although the dome is many metres above.\n\nThe tidal reference is restored. Resting mark: 0.'] },
};

export const puzzleNotes = {
  archive: ['arrival-a', 'arrival-b'], radio: ['radio-a', 'radio-b', 'archive-result'],
  tide: ['tide-a', 'tide-b'], meridian: ['meridian-rule', 'archive-result', 'radio-result', 'tide-result'],
};

export const hints = {
  archive: [
    ['到站簿在“现在”的桌上；另一半顺序记录藏在档案室的“回声”里。', 'The register is on the desk in the Present. The other half is in the archive’s Echo.'],
    ['先放第三位的日标、第五位的棱标。星标必须紧挨在日标前面。剩下两位再比较先后。', 'Place Sun third and Diamond fifth. Star must be immediately before Sun. Compare the remaining two.'],
    ['从左至右：潮 ≋、星 ✶、日 ⊙、峰 △、棱 ◇。', 'Left to right: Tide ≋, Star ✶, Sun ⊙, Peak △, Diamond ◇.'],
  ],
  radio: [
    ['需要档案室的到站顺序，以及信号室两种时间状态下的记录。', 'You need the archive’s arrivals and the records in both moments of the signal room.'],
    ['星标是第二位，所以第一频段是 2。再按磁带上的倍数与加法计算。', 'Star arrived second, so band one is 2. Apply the tape’s multiplication and addition.'],
    ['三个频段依次为 2、4、6。调好后锁定频段。', 'Set the bands to 2, 4, and 6, then lock the frequencies.'],
  ],
  tide: [
    ['回声里的水下刻字给出目标；现在的维修铭牌解释四个旋钮的联动方式。', 'The Echo’s underwater inscription gives the target. The Present’s service plate explains the coupled controls.'],
    ['目标是四个 0。先注意 D 每次会让第四针走两格。＋与−互为逆操作，可以大胆试；第三层提示会根据当前刻度给出解法。', 'Aim for four zeroes. D moves hand IV twice as far. + and − undo each other, so experiment freely. The final hint calculates a route from your current positions.'],
    ['', ''],
  ],
  meridian: [
    ['穹顶右侧的镜架铭文说明了三个轨道的参照。你可以在手记里同时查看三处校准结果。', 'The inscription beside the dome’s telescope explains the three references. Compare the calibrated results in your journal.'],
    ['由内向外：停潮刻度、日标的位次、第三频段。把读数带到“回声”里。', 'Inside out: the tide’s resting mark, Sun’s arrival position, the third radio band. Take these readings into the Echo.'],
    ['内轨 0、中轨 3、外轨 6。在回声中锚定，然后切回现在释放主镜。', 'Inner 0, middle 3, outer 6. Anchor in the Echo, then return to the Present to release the meridian.'],
  ],
};
